fix content-length calculation on range requests
tower-rs/tower-http pull request #228
Opened 2022-03-08 13:38 UTC by moumar

hello,

content-length response header on range requests should represent the length of the returned range, not the length of the whole file.

more explanations here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

Best regards.

2022-03-08 13:46 UTC, davidpdrsn requested changes
Oh good catch! I wonder how we missed this 🤔 

Some tests for this would be great!

2022-03-08 13:59 UTC, davidpdrsn commented on tower-http/src/services/fs/serve_dir.rs
> +            (bytes_end_incl - bytes_start_incl + 1).to_string()
Ah my bad. I see this is in a test which you updated. Nvm

2022-03-08 14:03 UTC, MarcusGrass commented
I see there are a few tests running on both head-requests and range-requests checking the content-length and that you fixed the test that should return something other than the full file size. It seems that I both wrote a bug and a bugged test to go with it. Really nice catch, thank you!

2022-03-09 01:48 UTC, adumbidiot commented
I think this closes #197. I’ll try to test it out later

2022-03-09 10:03 UTC, davidpdrsn approved these changes
I think this looks good. Will wait for @adumbidiot to report back before merging.

2022-03-09 20:02 UTC, adumbidiot commented
Just tested, this fixes #197

2022-03-09 20:09 UTC, davidpdrsn commented
Great! I think I'll backport this to 0.2.x tomorrow while we work on 0.3.

2022-03-09 20:09 UTC, merged