Include grpc error message in tracing
tower-rs/tower-http pull request #422
Opened 2023-10-07 10:02 UTC by xiaoyawei

## Motivation

Currently the tracing middleware only captures the gRPC status code when extracting the error out of a http response. Besides the code, gRPC also requires a human-readable message for error handling, and it'll be useful in this message is extracted from the response as well.

## Solution

Per [gRPC over HTTP/2 Protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses), a percent-encoded message is included in `grpc-message` field in the response header / trailer. So this PR also extracts this value and include it in the extracted `GrpcFailureClass`, such that the downstream usages can use this message for tracing.

2026-05-21 05:12 UTC, jlizen requested changes
@xiaoyawei I'm on board with adding this functionality in, it does match the protocol spec, but some concerns with the specific implementation, see comments.

Please let me know if you are interested in working on this within ~1 month, I know it's a very old PR. Else I might push my suggestions on top since I'm anyway planning a breaking release soon.

----

General feedback:

This is a breaking change to a public type (which I see no good way to avoid), so let's make the commit message and pr description something like:
```
refactor!: include grpc error message in tracing
```

We do need test coverage as well:
- happy path (percent-encoded value)
- invalid percent-encoding
- invalid utf-8
- unknown status code
- empty grpc-message header value

2026-05-21 05:12 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +#[derive(Clone, Copy, Debug, PartialEq, Eq)]
We should add `#[repr(i32)]` rather than relying on the default `isize` repr while casting

2026-05-21 05:12 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +    let code = or_else!(GrpcCode::from_bytes(code.as_ref()), HeaderNotGrpcCode);
This is a behavioral regression. Previously, >16 would be propagated as non-success, now they are converted to `HeaderNotGrpcCode`.

The spec states: 
> gRPC libraries that encounter values outside this range must either propagate them directly or convert them to UNKNOWN.

[ref](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md)

2026-05-21 05:12 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +    let code = or_else!(GrpcCode::from_bytes(code.as_ref()), HeaderNotGrpcCode);
Let's make sure we have a test for this after fixing.

2026-05-21 05:12 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +                    .ok()
Currently we are throwing away the full value in case of non-utf8. It would be more in the spirit of the spec to do a lossy decode:
```
percent_decode(header.as_bytes()).decode_utf8_lossy()
```

> Implementations must not error due to receiving an invalid ASCII-Value that's a valid field-value in HTTP, but the precise behavior is not strictly defined: they may throw the value away or accept the value. If accepted, care must be taken to make sure that the application is permitted to echo the value back as metadata. For example, if the metadata is provided to the application as a list in a request, the application should not trigger an error by providing that same list as the metadata in the response.

[ref](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses)

2026-05-21 05:12 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
>  pub enum GrpcCode {
Let's tag this as `#[non_exhaustive]` while we are anyway breaking semver

2026-05-21 05:12 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
>  pub enum GrpcFailureClass {
While we are anyway breaking semver, let's make this `#[non_exhaustive]`.

2026-05-21 05:13 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
>  impl fmt::Display for GrpcFailureClass {
Let's also impl `std::error::Error` for `GrpcFailureClass` while we are anyway touching it

2026-05-21 05:17 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +    pub(crate) fn code(&self) -> GrpcCode {
Let's promote this from `pub(crate)` to `pub`, it seems useful

2026-05-21 05:17 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +impl GrpcStatus {
Let's also add a `pub fn message()-> Option<&str>` to avoid forcing usage of the format machinery to peek the message

2026-05-21 05:25 UTC, xiaoyawei commented
@jlizen Thanks for the review. I will try to address your comments and push something in the next a couple of days

2026-05-22 02:51 UTC, xiaoyawei commented
Hey @jlizen , would you take another look when you have time?

2026-05-22 04:27 UTC, jlizen requested changes
The refactor looks great, a few more small things, then it's ready to merge.

2026-05-22 04:27 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +        .and_then(|header| header.to_str().ok().map(|s| s.to_owned()));
this path also needs the `.decode_utf_lossy()` handling

2026-05-22 04:27 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +        message: "bad%2Gencode",
this is good, but let's also have a similar test that is valid utf-8

2026-05-22 04:27 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
> +    #[cfg(feature = "trace")]
As best as i can tell this split only exists to avoid depending on `percent-encoding` for non-trace, but it's a tiny no-dependencies dependency, I probably wouldn't bother with it in favor of simplifying.

2026-05-22 04:27 UTC, jlizen commented on tower-http/src/classify/grpc_errors_as_failures.rs
Let's also have a test probing that `GrpcCode::Ok` (code 0) is classified as a success

2026-05-22 06:26 UTC, xiaoyawei commented
@jlizen See how your comments are addressed in the 3rd commit of this PR

2026-05-22 06:30 UTC, jlizen approved these changes
Looks great! Thanks for the contribution.

Aiming to get this released within the next ~2 weeks.

2026-05-22 06:30 UTC, merged