Add `prepend_path` option
tower-rs/tower-http pull request #486
Opened 2024-04-27 18:00 UTC by maxi0604

## Motivation

Currently `ServeDir` assumes that the files are served from `/`, which makes breaks trailing slash redirects in some configurations like a reverse proxy that redirects `/somePath/*` to it or a scenario where `axum::Router::nest_service` is used.

## Solution
This allows the user to pass in a string that is prepended to the redirect path.

2024-05-02 18:59 UTC, jplatte commented
Hey, thanks for the PR! I think we should have something like this (as indicated in my last comment on #413), but.. naming is hard. I've been considering something like `.prefix("/static", PrefixMode::PrependOnRedirect)` (where the other `PrefixMode` would be to strip the prefix on incoming requests before filesystem lookup _and_ prepend it on redirects), but this would require users to import that enum, and I still don't know what name to give the other prefix mode 😄

I guess since axum `.nest()` is the most important use case and it's easy enough to implement something like it elsewhere, we could start with just this "mode", i.e. a function like what you added but with a clearer name.

So if you don't care much about the naming or what exactly the API looks like, I would recommend you rename `prepend_path` to `redirect_path_prefix`. Otherwise, I'm curious to hear your thoughts!

2024-05-02 19:47 UTC, maxi0604 commented
Thanks for the review

> I guess since axum `.nest()` is the most important use case and it's easy enough to implement something like it elsewhere, we could start with just this "mode", i.e. a function like what you added but with a clearer name.
I think this one solves the more pressing issue with the redirects.

You could use a workaround like putting the files at `base-folder/prefix/...` if you are (somehow) getting requests for paths with the prefix; but as suggested in the issue, fixing the trailing slash redirects would require intercepting the response. 

A separate option to strip an arbitrary prefix from the file path could also be added if that workaround doesn't work for someone. (Maybe `strip_path_prefix`) This would have to be explained in the documentation but ultimately provides more flexibility (With the two options combined, you could replace a prefix with another one.)

> So if you don't care much about the naming or what exactly the API looks like, I would recommend you rename `prepend_path` to `redirect_path_prefix`. Otherwise, I'm curious to hear your thoughts!

I've renamed it to `redirect_path_prefix`, that does sound like a more reasonable name. I think this already solves an immediate issue while more flexibility could be added later.

2024-05-02 19:50 UTC, maxi0604 commented
I don't know why the cargo-hack test is failing, it seems unrelated to me.

2026-05-22 06:42 UTC, jlizen requested changes
@claraphyll sorry for the extended delay in the review...

The new naming and API seems fine to me. Glad to approve this with some small changes, and it needs a rebase.

Or if you no longer have time to work on it, no problem, I am happy to finish it up.

2026-05-22 06:42 UTC, jlizen commented on tower-http/src/services/fs/serve_dir/mod.rs
> +            redirect_path_prefix: "".to_string(),
This should forward the existing value rather than discarding it

2026-05-22 06:42 UTC, jlizen commented on tower-http/src/services/fs/serve_dir/open_file.rs
> +        let location = HeaderValue::from_str(&location_string).unwrap();
We shouldn't panic here. The uri unwrapped in existing code but was already validated, we should instead propagate the error. Since this PR main has refactored to use `OpenFileOutput::InvalidRedirectUri` if you rebase.

2026-05-22 06:42 UTC, jlizen commented on tower-http/src/services/fs/serve_dir/mod.rs
> +    pub fn redirect_path_prefix(mut self, path: String) -> Self {
This should accept `impl Into<String>`

2026-05-22 06:42 UTC, jlizen commented on tower-http/src/services/fs/serve_dir/mod.rs
> +    /// In that example, you should pass in "/static" so that a trailing slash redirect does not
```suggestion
    /// In that example, you should pass in `/static` so that a trailing slash redirect does not
```

2026-05-22 06:42 UTC, jlizen commented on tower-http/src/services/fs/serve_dir/mod.rs
> +    /// This is useful when you want to serve the files at another location than "/", for example
```suggestion
    /// This is useful when you want to serve the files at another location than `/`, for example
```

2026-05-22 06:42 UTC, jlizen commented on tower-http/src/services/fs/serve_dir/tests.rs
> +#[tokio::test]
We should also test:
- `redirect_path_prefix` + `fallback()`
- prefix with trailing slash
- empty prefix (or should we reject that during validation?)
- combination with query parameters
- combination with percent-encoded path

2026-06-08 15:29 UTC, jlizen approved these changes
Thanks!

2026-06-08 15:31 UTC, merged

2026-06-09 00:35 UTC, samanpa commented
Can a new release be made with this feature

2026-06-09 01:01 UTC, jlizen commented
Preparing a release, just waiting on a few more PRs.