Add `html_as_default_extension` option to `ServeDir`
tower-rs/tower-http pull request #519
Opened 2024-09-22 00:15 UTC by its-the-shrimp

## Motivation

It's common for file servers to add an `.html` file extension to the requested path if no file extension is provided, to allow for more concise & human-readable links, e.g. for a request of `/dashboard`, return `/dashboard.html`

## Solution

Add a `html_as_default_extension` option to the `ServeDir` service, which will be `true` by default, to be in tune with [`append_index_html_on_directories`](https://docs.rs/tower-http/latest/tower_http/services/struct.ServeDir.html#method.append_index_html_on_directories)

2026-05-21 04:38 UTC, jlizen requested changes
@its-the-shrimp i'm fine to add this API, it is indeed a common convention, but it should default to false

Let me know if you no longer have time to work on this, I don't mind finishing it up.

2026-05-26 11:25 UTC, its-the-shrimp commented
Done that

2026-05-27 18:22 UTC, jlizen reviewed
@its-the-shrimp - Impl looks good, thanks! Can we also have a test case for when the suffix is added? Glad to merge with that in place.

2026-05-28 23:21 UTC, jlizen approved these changes
Added some tests and a bugfix. Thanks for the contribution!

2026-05-28 23:23 UTC, merged